### ISSUE TITLE
Triple Scroll Bars

### ISSUE THREAD

**Issue by AoiTsurara** [konpekopeko/Emtech#1]
There seems to be 2 extra scroll bars on the main website. Probably because of different screen resolutions and sizing. no, im boiut to kaaaammm ahhhhh yameteeeee im boutodieeeeeeee.

**Comment by konpekopeko** [comment]
> There seems to be 2 extra scroll bars on the main website. Probably because of different screen resolutions and sizing. no, im boiut to kaaaammm ahhhhh yameteeeee im boutodieeeeeeee.

is for an assignment bro, low quality cuz dont need dat grades
